### ISSUE TITLE
Sliding for opening the covers in HomeAssistant

### ISSUE THREAD

**Issue by fft1010** [rstrouse/ESPSomfy-RTS#356]
Hi,
I do not exactly know if this is the right place, but I think here is the target audience :-) By accident I found out, that I could open the sliders in any opening percentage I want to use. In  another small project I am using "sliders" from here: https://github.com/thomasloven/lovelace-slider-entity-row

If you combine this, you can get something like

![screen-2024-05-03-06-52-03](https://github.com/rstrouse/ESPSomfy-RTS/assets/18101485/e5234600-a73a-4650-9836-f8584eba6e20)

which is a card in HA that looks like: (Rolladen is one cover, Rolläden are more than one cover.

```
type: entities
state_color: true
title: Rolläden
show_header_toggle: true
entities:
  - entity: cover.rolladen
    name: links
    type: custom:slider-entity-row
    step: 1
    full_row: true
    toggle: false
    hide_state: false
    hide_when_off: false
    show_icon: false
    colorize: true
  - entity: cover.l1
    name: L1
    type: custom:slider-entity-row
    step: 1
    toggle: true
  - entity: cover.l2
    name: L2
    type: custom:slider-entity-row
    step: 1
    toggle: true
  - entity: cover.l3
    name: L3
    type: custom:slider-entity-row
    step: 1
    toggle: true
  - entity: cover.l4
    name: L4
    type: custom:slider-entity-row
    step: 1
    toggle: true
  - entity: cover.r1
    name: R1
    type: custom:slider-entity-row
    step: 1
    toggle: true
  - entity: cover.r2
    name: R2
    type: custom:slider-entity-row
    step: 1
    toggle: true
  - entity: cover.r3
    name: R3
    type: custom:slider-entity-row
    step: 1
    toggle: true
  - entity: cover.r4
    name: R4
    type: custom:slider-entity-row
    step: 1
    toggle: true
```

in ESPSSomfy I had to add a "repeat command" for every of my 8 covers. 2 was enough. Before not adding this, not all covers seem to get the commands. 
![repeat-command](https://github.com/rstrouse/ESPSomfy-RTS/assets/18101485/e71cb390-aaec-4670-adf9-51da5650dc04)

I hope this helpy others as well. If you think there is a better place for this, than just tell me here, and I can put it somewhere else.

Have fun.
Juergen
